# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9489c4acccd2441d11b4c8fa1db611b6b01aca8aae2cd4663a8fcac086867323fea98827ce9e45cd94b4ff79a1b00037b3647cd8bb9468695075589287faf065

test:
  secret_key_base: aada033f5be726775fc9afa135f997337dec2c83bc8a0ed58b590485725d9fb0cc3b1e45d8eaf7e4a9d8f732ffcd5ac97e6224f2655b9a85abbee46801277efb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
